### ISSUE TITLE
Review of 27a2eb8 - Zoom Action

### ISSUE THREAD

**Issue by Salomon88** [Salomon88/GcViewerPlugin#16]
Make review of 27a2eb8 - #9  issue. I accidentally made commit to master

**Comment by xnike** [comment]
As for now I see only 4 minor issue:

* Not using `Code -> Reformat Code` before commit to have same default style
* Not tuned at `Settings -> Editor -> Code Style -> Java -> Imports`  values of  `Class count to use import with` and `Names count to use static import with` to `100` to better understanding where everything were imported from on code skimming. 
* Not using `gcviewerBundle.properties` bundle for short name `Zoom` to avoid hardcoding
* `System.out.println` could be removed.

Other things like using `static` for `ZoomActionGroup`. exposing `GCDocumentWrapper::getModelChart` are so so.
Looks like `ToggleZoomAction` is too specific and could be easily replaced with anonymous `ToggleAction`. Action group could contain `isSelected` and `setSelected` methods passed to mention anonymous `ToggleAction` instances. Moreover group action short name and icon via constructor, so everything will in one place and better maintainable. So looks like that it could be rewritten in more generic way or just replaced with anonymous classes instances.
But I'm not insisting on it, it's just another point of view.
